export const types = Object.freeze({
  // Sync
  USER_START_FETCHING: 'USER_START_FETCHING',
  USER_STOP_FETCHING: 'USER_STOP_FETCHING',
  USER_FILL: 'USER_FILL',
  USER_SET_FETCHING_ERROR: 'USER_SET_FETCHING_ERROR',

  USER_FETC_ASYNC: 'USER_FETC_ASYNC',

  ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
  ADD_USER_FAILURE: 'ADD_USER_FAILURE',
});